Vagrant.configure("2") do |config|
  config.vm.box = "xcoo/bionic64"
  config.vm.network "private_network", ip: "192.168.33.22"
  config.vm.hostname = "webadv"
  config.vm.provider "virtualbox" do |vb|
      vb.memory = "2048"
      vb.customize ["modifyvm", :id, "--cableconnected1", "on"]
  end
  config.vm.provision :shell, path: "bootstrap.sh"
end
