// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Stage_API.Data;

namespace Stage_API.Data.Migrations
{
    [DbContext(typeof(StageContext))]
    partial class StageContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            RoleId = 1
                        },
                        new
                        {
                            UserId = 2,
                            RoleId = 1
                        },
                        new
                        {
                            UserId = 3,
                            RoleId = 1
                        },
                        new
                        {
                            UserId = 4,
                            RoleId = 1
                        },
                        new
                        {
                            UserId = 5,
                            RoleId = 2
                        },
                        new
                        {
                            UserId = 6,
                            RoleId = 2
                        },
                        new
                        {
                            UserId = 7,
                            RoleId = 2
                        },
                        new
                        {
                            UserId = 8,
                            RoleId = 2
                        },
                        new
                        {
                            UserId = 9,
                            RoleId = 2
                        },
                        new
                        {
                            UserId = 10,
                            RoleId = 2
                        },
                        new
                        {
                            UserId = 11,
                            RoleId = 3
                        },
                        new
                        {
                            UserId = 12,
                            RoleId = 3
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("Stage_API.Domain.Bedrijfspromotor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Naam")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefoonnummer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Titel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Voornaam")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Bedrijfspromotors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "promotie@cegeka.be",
                            Naam = "van Brussel",
                            Telefoonnummer = "016325485",
                            Titel = "Dhr",
                            Voornaam = "Laurens"
                        },
                        new
                        {
                            Id = 2,
                            Email = "promotie@tesla.be",
                            Naam = "Grimes",
                            Telefoonnummer = "016325485",
                            Titel = "Mevrouw",
                            Voornaam = "Claire"
                        },
                        new
                        {
                            Id = 3,
                            Email = "promotie@microsoft.nl",
                            Naam = "Waterslaeghers",
                            Telefoonnummer = "0479654321",
                            Titel = "Dhr",
                            Voornaam = "Xavier"
                        },
                        new
                        {
                            Id = 4,
                            Email = "promotie@dell.be",
                            Naam = "Boma",
                            Telefoonnummer = "0469696969",
                            Titel = "Dhr",
                            Voornaam = "Balthazar"
                        });
                });

            modelBuilder.Entity("Stage_API.Domain.Classes.Comment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("StagevoorstelId")
                        .HasColumnType("int");

                    b.Property<string>("Text")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("StagevoorstelId");

                    b.HasIndex("UserId");

                    b.ToTable("Comments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Date = new DateTime(2020, 5, 20, 15, 48, 0, 0, DateTimeKind.Local),
                            StagevoorstelId = 1,
                            Text = "Het onderzoeksthema is niet ingevuld. Kan dit zo spoedig mogelijk ingevuld worden?",
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            Date = new DateTime(2020, 5, 21, 8, 40, 0, 0, DateTimeKind.Local),
                            StagevoorstelId = 1,
                            Text = "We zullen er eens over nadenken en dit zo spoedig mogelijk in gaan vullen.",
                            UserId = 11
                        },
                        new
                        {
                            Id = 3,
                            Date = new DateTime(2020, 5, 21, 9, 24, 0, 0, DateTimeKind.Local),
                            StagevoorstelId = 2,
                            Text = "Wat wordt er precies bedoeld met 'De stagiairs zullen leren werken met AI om autopiloot van Tesla te verbeteren'? Dit is niet voldoende, gelieve dit te verduidelijken.",
                            UserId = 1
                        });
                });

            modelBuilder.Entity("Stage_API.Domain.Classes.ResetPasswordRequest", b =>
                {
                    b.Property<Guid>("PasswordResetToken")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsConsumed")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ResetRequestDateTime")
                        .HasColumnType("datetime2");

                    b.HasKey("PasswordResetToken");

                    b.ToTable("ResetPasswordRequests");
                });

            modelBuilder.Entity("Stage_API.Domain.Contactpersoon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Naam")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefoonnummer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Titel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Voornaam")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Contactpersonen");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "contact@cegeka.be",
                            Naam = "Koekenpan",
                            Telefoonnummer = "0486321465",
                            Titel = "Dhr",
                            Voornaam = "Jan"
                        },
                        new
                        {
                            Id = 2,
                            Email = "contact@tesla.be",
                            Naam = "Musk",
                            Telefoonnummer = "04765413212",
                            Titel = "Dhr",
                            Voornaam = "Elon"
                        },
                        new
                        {
                            Id = 3,
                            Email = "contact@microsoft.nl",
                            Naam = "Waterslaeghers",
                            Telefoonnummer = "0478514654",
                            Titel = "Mevrouw",
                            Voornaam = "Carmen"
                        },
                        new
                        {
                            Id = 4,
                            Email = "contact@dell.be",
                            Naam = "Vertongen",
                            Telefoonnummer = "0498765432",
                            Titel = "Dhr",
                            Voornaam = "Mark"
                        });
                });

            modelBuilder.Entity("Stage_API.Domain.Message", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("EmailReceiver")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmailSender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReceiverFirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ReceiverId")
                        .HasColumnType("int");

                    b.Property<string>("ReceiverLastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SenderFirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SenderId")
                        .HasColumnType("int");

                    b.Property<string>("SenderLastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("Stage_API.Domain.Relations.ReviewerStagevoorstelToegewezen", b =>
                {
                    b.Property<int>("ReviewerId")
                        .HasColumnType("int");

                    b.Property<int>("StagevoorstelId")
                        .HasColumnType("int");

                    b.HasKey("ReviewerId", "StagevoorstelId");

                    b.HasIndex("StagevoorstelId");

                    b.ToTable("ToegewezenStagevoorstellenReviewer");

                    b.HasData(
                        new
                        {
                            ReviewerId = 2,
                            StagevoorstelId = 1
                        },
                        new
                        {
                            ReviewerId = 2,
                            StagevoorstelId = 2
                        },
                        new
                        {
                            ReviewerId = 3,
                            StagevoorstelId = 2
                        },
                        new
                        {
                            ReviewerId = 3,
                            StagevoorstelId = 3
                        },
                        new
                        {
                            ReviewerId = 3,
                            StagevoorstelId = 4
                        },
                        new
                        {
                            ReviewerId = 3,
                            StagevoorstelId = 5
                        },
                        new
                        {
                            ReviewerId = 4,
                            StagevoorstelId = 3
                        },
                        new
                        {
                            ReviewerId = 4,
                            StagevoorstelId = 6
                        },
                        new
                        {
                            ReviewerId = 4,
                            StagevoorstelId = 7
                        },
                        new
                        {
                            ReviewerId = 4,
                            StagevoorstelId = 8
                        });
                });

            modelBuilder.Entity("Stage_API.Domain.Review", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("ReviewerId")
                        .HasColumnType("int");

                    b.Property<int>("StagevoorstelId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("StatusVoorstel")
                        .HasColumnType("int");

                    b.Property<string>("Text")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ReviewerId");

                    b.HasIndex("StagevoorstelId");

                    b.ToTable("Reviews");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Date = new DateTime(2020, 5, 21, 20, 16, 39, 529, DateTimeKind.Local).AddTicks(3429),
                            ReviewerId = 2,
                            StagevoorstelId = 1,
                            Status = 2,
                            StatusVoorstel = 2
                        },
                        new
                        {
                            Id = 2,
                            Date = new DateTime(2020, 5, 21, 20, 16, 39, 529, DateTimeKind.Local).AddTicks(5132),
                            ReviewerId = 2,
                            StagevoorstelId = 2,
                            Status = 2,
                            StatusVoorstel = 2
                        },
                        new
                        {
                            Id = 3,
                            Date = new DateTime(2020, 5, 21, 20, 16, 39, 529, DateTimeKind.Local).AddTicks(5175),
                            ReviewerId = 3,
                            StagevoorstelId = 3,
                            Status = 2,
                            StatusVoorstel = 2
                        },
                        new
                        {
                            Id = 4,
                            Date = new DateTime(2020, 5, 21, 20, 16, 39, 529, DateTimeKind.Local).AddTicks(5179),
                            ReviewerId = 3,
                            StagevoorstelId = 4,
                            Status = 0,
                            StatusVoorstel = 2
                        },
                        new
                        {
                            Id = 5,
                            Date = new DateTime(2020, 5, 21, 20, 16, 39, 529, DateTimeKind.Local).AddTicks(5183),
                            ReviewerId = 3,
                            StagevoorstelId = 5,
                            Status = 2,
                            StatusVoorstel = 1,
                            Text = "Te grote verantwoordelijkheid.."
                        },
                        new
                        {
                            Id = 6,
                            Date = new DateTime(2020, 5, 21, 20, 16, 39, 529, DateTimeKind.Local).AddTicks(5528),
                            ReviewerId = 4,
                            StagevoorstelId = 6,
                            Status = 2,
                            StatusVoorstel = 0,
                            Text = "Over welke tools gaat het hier precies? We hadden graag wat meer informatie zodat de studenten ook weten waar ze aan toe zijn."
                        },
                        new
                        {
                            Id = 7,
                            Date = new DateTime(2020, 5, 21, 20, 16, 39, 529, DateTimeKind.Local).AddTicks(5552),
                            ReviewerId = 4,
                            StagevoorstelId = 7,
                            Status = 2,
                            StatusVoorstel = 0,
                            Text = "Storingen van welke aard? Moeilijkheidsgraad?"
                        },
                        new
                        {
                            Id = 8,
                            Date = new DateTime(2020, 5, 21, 20, 16, 39, 529, DateTimeKind.Local).AddTicks(5555),
                            ReviewerId = 4,
                            StagevoorstelId = 8,
                            Status = 1,
                            StatusVoorstel = 1,
                            Text = "Slaat helemaal nergens op!"
                        });
                });

            modelBuilder.Entity("Stage_API.Domain.ReviewerStagevoorstelFavoriet", b =>
                {
                    b.Property<int>("ReviewerId")
                        .HasColumnType("int");

                    b.Property<int>("StagevoorstelId")
                        .HasColumnType("int");

                    b.HasKey("ReviewerId", "StagevoorstelId");

                    b.HasIndex("StagevoorstelId");

                    b.ToTable("FavorietenStagevoorstellenReviewer");

                    b.HasData(
                        new
                        {
                            ReviewerId = 2,
                            StagevoorstelId = 1
                        },
                        new
                        {
                            ReviewerId = 3,
                            StagevoorstelId = 4
                        },
                        new
                        {
                            ReviewerId = 4,
                            StagevoorstelId = 7
                        });
                });

            modelBuilder.Entity("Stage_API.Domain.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedName")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ConcurrencyStamp = "be6b7ddb-14f5-45d6-8bd9-b674eb58919e",
                            Name = "reviewer",
                            NormalizedName = "REVIEWER"
                        },
                        new
                        {
                            Id = 2,
                            ConcurrencyStamp = "07f55e06-0fbd-493a-8c86-aba43389e594",
                            Name = "student",
                            NormalizedName = "STUDENT"
                        },
                        new
                        {
                            Id = 3,
                            ConcurrencyStamp = "b3edda42-525e-48ca-a8cf-e6bc0c3ebb50",
                            Name = "bedrijf",
                            NormalizedName = "BEDRIJF"
                        });
                });

            modelBuilder.Entity("Stage_API.Domain.Stagevoorstel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AantalGewensteStagiairs")
                        .HasColumnType("int");

                    b.Property<string>("Adres")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AfstudeerrichtingVoorkeur")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("BedrijfId")
                        .HasColumnType("int");

                    b.Property<string>("Bemerkingen")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Gemeente")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GereserveerdeStudenten")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Omgeving")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OmgevingOmschrijving")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Onderzoeksthema")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OpdrachtOmschrijving")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Periode")
                        .HasColumnType("int");

                    b.Property<string>("Randvoorwaarden")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StageITMedewerkers")
                        .HasColumnType("int");

                    b.Property<string>("StagePostcode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Titel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Verwachtingen")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("BedrijfId");

                    b.ToTable("Stagevoorstellen");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AantalGewensteStagiairs = 2,
                            Adres = "Kempische Steenweg 307",
                            AfstudeerrichtingVoorkeur = "applicatieOntwikkeling",
                            BedrijfId = 11,
                            Bemerkingen = "/",
                            Date = new DateTime(2020, 5, 21, 20, 16, 39, 526, DateTimeKind.Local).AddTicks(4942),
                            Gemeente = "Hasselt",
                            GereserveerdeStudenten = "/",
                            Omgeving = "dotNet,web,mobile",
                            OmgevingOmschrijving = "/",
                            Onderzoeksthema = "/",
                            OpdrachtOmschrijving = "De stagiair zal werken aan interne software toepassingen.",
                            Periode = 2,
                            Randvoorwaarden = "Rijbewijs",
                            StageITMedewerkers = 200,
                            StagePostcode = "3500",
                            Status = 2,
                            Titel = ".Net Developer",
                            Verwachtingen = "CV"
                        },
                        new
                        {
                            Id = 2,
                            AantalGewensteStagiairs = 2,
                            Adres = "Boomse Steenweg 8",
                            AfstudeerrichtingVoorkeur = "applicatieOntwikkeling,AI",
                            BedrijfId = 12,
                            Bemerkingen = "/",
                            Date = new DateTime(2020, 5, 21, 20, 16, 39, 529, DateTimeKind.Local).AddTicks(2176),
                            Gemeente = "Aartselaar",
                            GereserveerdeStudenten = "/",
                            Omgeving = "anders",
                            OmgevingOmschrijving = "De stagiairs zullen hier voornamelijk werken met Python.",
                            Onderzoeksthema = "Tesla autopiloot",
                            OpdrachtOmschrijving = "De stagiairs zullen leren werken met AI om autopiloot van Tesla te verbeteren. Voor vragen kunnen ze altijd terecht bij onze professionals.",
                            Periode = 1,
                            Randvoorwaarden = "Rijbewijs",
                            StageITMedewerkers = 200,
                            StagePostcode = "2630",
                            Status = 2,
                            Titel = "Develop the future! Advance Tesla's autopilot technology!",
                            Verwachtingen = "vergoeding, sollicitatiegesprek"
                        },
                        new
                        {
                            Id = 3,
                            AantalGewensteStagiairs = 2,
                            Adres = "Boomse Steenweg 8",
                            AfstudeerrichtingVoorkeur = "applicatieOntwikkeling,netwerkBeheer",
                            BedrijfId = 12,
                            Bemerkingen = "/",
                            Date = new DateTime(2020, 5, 21, 20, 16, 39, 529, DateTimeKind.Local).AddTicks(2358),
                            Gemeente = "Aartselaar",
                            GereserveerdeStudenten = "/",
                            Omgeving = "java,dotNet,web,mobile,systemenNetwerken,softwareTesting,anders",
                            OmgevingOmschrijving = @"Teamwerk in een open en dynamische sfeer.
                        Begeleiding op maat! Jij geeft aan waar je interesses liggen. We bieden verschillende carrièrepaden aan, en kijken samen hoe we je verder kunnen helpen ontplooien.",
                            Onderzoeksthema = "Onderhoud van alle storagecomponenten.",
                            OpdrachtOmschrijving = @"Als Enterprise Storage Engineer installeer en configureer je alle storagecomponenten van Cegeka of de klanten van Cegeka (Switches, SAN, NAS, …).
                        Je werkt mee aan de verdere uitbouw van het storage platform en de dienstverlenging.
                        Je zorgt ervoor dat de documentatie, instructies, procedures en kennis up - to - date worden gehouden.
                        Je bepaalt mee de standaarden en best practices voor de infrastructuur / applicaties teneinde een duurzame oplossing te kunnen bieden in lijn met de verwachtingen van de klant.
                        Samen met je collega’s sta je stand - by om 24 uur service te kunnen leveren.
                        Je werkt mee aan het automatiseren van taken die momenteel manueel gebeuren.
                        Je neemt op regelmatige tijdstippen zelfstandig een project op.",
                            Periode = 1,
                            Randvoorwaarden = "Beschikt over een rijbewijs.",
                            StageITMedewerkers = 102,
                            StagePostcode = "2630",
                            Status = 2,
                            Titel = "Enterprise Storage Engineer",
                            Verwachtingen = "vergoeding"
                        },
                        new
                        {
                            Id = 4,
                            AantalGewensteStagiairs = 1,
                            Adres = "Doornveld 130",
                            AfstudeerrichtingVoorkeur = "applicatieOntwikkeling",
                            BedrijfId = 14,
                            Bemerkingen = "/",
                            Date = new DateTime(2020, 5, 21, 20, 16, 39, 529, DateTimeKind.Local).AddTicks(2369),
                            Gemeente = "Asse",
                            GereserveerdeStudenten = "/",
                            Omgeving = "java,dotNet",
                            OmgevingOmschrijving = @"Ruime ervaring met professionele enterprise Java of .NET is een must.
                    Ook beschik je over ervaring met analyse, design, implementatie en oplevering van applicaties.
                    Jij kan de architectuur van complexe applicaties uittekenen, rekening houdend met alle niet-functionele vereisten zoals security, performantie, scalability, ... en je kan deze ook uitdragen naar het team.
                    Met jouw expertise heb jij een duidelijk zicht op de (technische) risico’s wat betreft impact en probabiliteit en voorziet strategieën om deze te mitigeren.
                    Je hebt een brede kennis van én ervaring met Web en Databasetechnologieën, communicatieprotocolen, integratietechnieken, gedistribueerde systemen, Devops, security, ….
                    O.O., design patterns, domain-driven design, refactoring en unit testing zijn zeer vertrouwde begrippen voor jou.
                    Scrum en eXtreme Programming zijn twee agile ontwikkelingsmethodologieën die je met plezier en kennis van zaken toepast.
                    Binnen de resultaatsgerichte, no-nonsens aanpak van een groeiend bedrijf als Cegeka, voel jij je onmiddellijk thuis.
                    Een sterke communicator, zowel binnen je team als naar de klant toe.
                    Je bent leergierig, stressbestendig en pragmatisch.",
                            Onderzoeksthema = "analyse, design, implementatie en oplevering van applicaties",
                            OpdrachtOmschrijving = @"Het sturen van de architectuur, het design en development van innovatieve ontwikkelingsprojecten voor klanten. Zowel voor mid-scale als large-scale applicaties.
                    Uitwerken van complexe bedrijfstoepassingen. Je doet dit samen met een team van gedreven professionals. Jij draagt de technische verantwoordelijkheid.
                    Hands-on development en coaching van developers o.a. via pair programming.
                    Communiceren met klanten en meewerken aan offertes.
                    Het opstarten van innovation centers rond de laatste trends binnen je vakdomein.",
                            Periode = 3,
                            Randvoorwaarden = "Uitgebreide kennis over Java en C#.",
                            StageITMedewerkers = 186,
                            StagePostcode = "1731",
                            Status = 2,
                            Titel = "Software Architect",
                            Verwachtingen = "geen"
                        },
                        new
                        {
                            Id = 5,
                            AantalGewensteStagiairs = 1,
                            Adres = "Evert van de Beekstraat 354",
                            AfstudeerrichtingVoorkeur = "netwerkBeheer",
                            BedrijfId = 13,
                            Bemerkingen = "/",
                            Date = new DateTime(2020, 5, 21, 20, 16, 39, 529, DateTimeKind.Local).AddTicks(2375),
                            Gemeente = "Schiphol",
                            GereserveerdeStudenten = "/",
                            Omgeving = "systemenNetwerken,softwareTesting",
                            OmgevingOmschrijving = "Je staat in voor het operationeel beheer van het shared ICT infrastructuur platform dat opgezet is binnen de campus van Energyville, inclusief netwerk en security. Dit houdt onder meer in:Lokale aanwezigheid en assistentie bij het oplossen van incidenten met betrekking tot het shared platform;Assistentie bij oplossen van verzoeken met betrekking tot het shared platform(o.a.patching);Samenwerken met de EnergyVille leveranciers zoals SecureLink, Infrax, Konica, …Je staat in voor gebruikersadministratie: beheer van distributielijsten, security groups, …Je zorgt voor de goede werking van de technische componenten in de vergaderzalen(schermen, clickshares, telefoons).Je staat in voor het lokaal servermanagement: beheer van de verschillende hardware toestellen in de serverroom, opvolging hardware meldingen lokale servers, …",
                            Onderzoeksthema = "Docker",
                            OpdrachtOmschrijving = @"Je bent het lokaal aanspreekpunt voor nieuwe ICT infrastructuur aanvragen. Deze worden ter bespreking voorgelegd om tot een gepaste oplossing te komen.
                    Je coördineert de uitvoering van lokale ICT infrastructuurprojecten.
                    Je staat in voor de specifieke ondersteuning van VITO medewerkers die werkzaam zijn binnen Energyville:
                    Lokale logistieke en ICT technische ondersteuning met betrekking tot werkstations en mobiele toestellen in samenspraak met de servicedesk van VITO.
                    Geven van ICT intro sessies in Genk
                    Je bent lid van het ICT systeem- & netwerkteam van VITO en neemt deel aan de activiteiten en projecten binnen de scope van dit team.",
                            Periode = 1,
                            Randvoorwaarden = "/",
                            StageITMedewerkers = 3612,
                            StagePostcode = "1118CZ",
                            Status = 0,
                            Titel = "Cloud Native Engineer",
                            Verwachtingen = "sollicitatiegesprek,CV"
                        },
                        new
                        {
                            Id = 6,
                            AantalGewensteStagiairs = 1,
                            Adres = "Kempische Steenweg 307",
                            AfstudeerrichtingVoorkeur = "applicatieOntwikkeling",
                            BedrijfId = 11,
                            Bemerkingen = "/",
                            Date = new DateTime(2020, 5, 21, 20, 16, 39, 529, DateTimeKind.Local).AddTicks(2380),
                            Gemeente = "Hasselt",
                            GereserveerdeStudenten = "/",
                            Omgeving = "web,anders",
                            OmgevingOmschrijving = "/",
                            Onderzoeksthema = "/",
                            OpdrachtOmschrijving = "Instaan voor het onderhoud van het huidige platform én meewerken aan het uitbouwen en ontwikkelingen van nieuwe platformen en tools.",
                            Periode = 1,
                            Randvoorwaarden = "/",
                            StageITMedewerkers = 200,
                            StagePostcode = "3500",
                            Status = 0,
                            Titel = "PHP Developer",
                            Verwachtingen = "vergoeding"
                        },
                        new
                        {
                            Id = 7,
                            AantalGewensteStagiairs = 1,
                            Adres = "Boomse Steenweg 8",
                            AfstudeerrichtingVoorkeur = "applicatieOntwikkeling,AI",
                            BedrijfId = 12,
                            Bemerkingen = "/",
                            Date = new DateTime(2020, 5, 21, 20, 16, 39, 529, DateTimeKind.Local).AddTicks(2385),
                            Gemeente = "Aartselaar",
                            GereserveerdeStudenten = "/",
                            Omgeving = "anders",
                            OmgevingOmschrijving = @"Windows Client (7, 8,10) Windows Server systemen – 
                    begrip functionaliteiten AD, DNS, DHCP,…
                    Goed inzicht in de basis netwerkconfiguratie
                    Vlot Nederlands en Engels spreken, Frans is een plus..",
                            Onderzoeksthema = "MS Office",
                            OpdrachtOmschrijving = @"Je werkt binnen een team op de ICT servicedesk aan het operationeel gedeelte van de ICT omgeving (voornamelijk Windows).
                    Je behandelt ICT serviceaanvragen van gebruikers, lost storingen op en werkt zelfstandig of in team aan change requests binnen het domein van de computer- en netwerkinfrastructuur.
                    Je rapporteert herhalende storingen en risico’s en denkt mee met jouw collega’s hoe die op te lossen en te vermijden.
                    Je monitort de live systemen en grijpt in waar systeemstoringen zich voordoen of dreigen voor te doen.
                    Je leert de job kennen door interne opleidingen, al doende en eventueel via externe opleidingen. Je kan uiteraard rekenen op de steun en uitleg van jouw collega’s.
                    Je geeft sporadisch trainingen over nieuwe en bestaande softwarepakketten aan collega’s of klanten.",
                            Periode = 1,
                            Randvoorwaarden = "Social skills",
                            StageITMedewerkers = 200,
                            StagePostcode = "2630",
                            Status = 0,
                            Titel = "Helpdeskmedewerker",
                            Verwachtingen = "vergoeding, sollicitatiegesprek"
                        },
                        new
                        {
                            Id = 8,
                            AantalGewensteStagiairs = 2,
                            Adres = "Doornveld 130",
                            AfstudeerrichtingVoorkeur = "softwareManagement",
                            BedrijfId = 14,
                            Bemerkingen = "/",
                            Date = new DateTime(2020, 5, 21, 20, 16, 39, 529, DateTimeKind.Local).AddTicks(2390),
                            Gemeente = "Asse",
                            GereserveerdeStudenten = "/",
                            Omgeving = "softwareTesting",
                            OmgevingOmschrijving = @"Een afwisselende jobinhoud bij één van de belangrijkste onafhankelijke spelers in het domein van adviesverlening
                    De nodige kansen om je persoonlijk te ontplooien door een uniek en uitgebreid opleidingsaanbod
                    Je werkt in een familiale, multidisciplinaire organisatie gelegen in een aantrekkelijke filevrije omgeving
                    Leer je nieuwe collega’s alvast kennen (https://youtu.be/CVXH8OFfF1w)
                    Kortom, wij bieden “maetwerk”",
                            Onderzoeksthema = "Procesverbeteringen",
                            OpdrachtOmschrijving = @"Je bent verantwoordelijk voor het in kaart brengen van bedrijfsprocessen
                    Je werkt de processen verder uit en implementeert deze in een Business Process Management softwarepakket (K2).
                    Je beheert bestaande en nieuwe datasources en voegt deze samen tot een globale data omgeving
                    Je voert functionele analyses uit en denkt mee met de organisatie en eindgebruiker
                    Je documenteert en rapporteert rond projecten met alle betrokken partijen
                    Je zoekt continu mee naar procesverbeteringen
                    Je rapporteert rechtsreeks aan de IT Director
                    Je blijft op de hoogte van de nieuwste ontwikkelingen en trends op technologisch vlak",
                            Periode = 2,
                            Randvoorwaarden = "Beheersing van een Business Process Management softwarepakket",
                            StageITMedewerkers = 186,
                            StagePostcode = "1731",
                            Status = 1,
                            Titel = "Business Process Analyst ",
                            Verwachtingen = "CV"
                        });
                });

            modelBuilder.Entity("Stage_API.Domain.StudentStagevoorstelFavoriet", b =>
                {
                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.Property<int>("StagevoorstelId")
                        .HasColumnType("int");

                    b.HasKey("StudentId", "StagevoorstelId");

                    b.HasIndex("StagevoorstelId");

                    b.ToTable("FavorietenStagevoorstellenStudent");

                    b.HasData(
                        new
                        {
                            StudentId = 5,
                            StagevoorstelId = 3
                        },
                        new
                        {
                            StudentId = 6,
                            StagevoorstelId = 4
                        },
                        new
                        {
                            StudentId = 7,
                            StagevoorstelId = 1
                        },
                        new
                        {
                            StudentId = 8,
                            StagevoorstelId = 2
                        },
                        new
                        {
                            StudentId = 9,
                            StagevoorstelId = 2
                        },
                        new
                        {
                            StudentId = 10,
                            StagevoorstelId = 4
                        },
                        new
                        {
                            StudentId = 10,
                            StagevoorstelId = 2
                        });
                });

            modelBuilder.Entity("Stage_API.Domain.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("IsBedrijf")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Naam")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedEmail")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedUserName")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("Voornaam")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers");

                    b.HasDiscriminator<string>("Discriminator").HasValue("User");
                });

            modelBuilder.Entity("Stage_API.Domain.Bedrijf", b =>
                {
                    b.HasBaseType("Stage_API.Domain.User");

                    b.Property<int>("AantalBegeleidendeMedewerkers")
                        .HasColumnType("int");

                    b.Property<int>("AantalITMedewerkers")
                        .HasColumnType("int");

                    b.Property<int>("AantalMedewerkers")
                        .HasColumnType("int");

                    b.Property<string>("Adres")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("BedrijfspromotorId")
                        .HasColumnType("int");

                    b.Property<int>("ContactpersoonId")
                        .HasColumnType("int");

                    b.Property<string>("Gemeente")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Postcode")
                        .HasColumnType("nvarchar(max)");

                    b.HasIndex("BedrijfspromotorId");

                    b.HasIndex("ContactpersoonId");

                    b.HasDiscriminator().HasValue("Bedrijf");

                    b.HasData(
                        new
                        {
                            Id = 11,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "45b9da70-51bc-4219-8411-bbb54091a2af",
                            Email = "contact@cegeka.be",
                            EmailConfirmed = true,
                            IsBedrijf = true,
                            LockoutEnabled = true,
                            Naam = "Cegeka",
                            NormalizedEmail = "CONTACT@CEGEKA.BE",
                            NormalizedUserName = "CONTACT@CEGEKA.BE",
                            PasswordHash = "AQAAAAEAACcQAAAAEE3MADTcj5R9NBdPZGuSrqvcfisB2jZdZoPa3+AbxcGsaSOQAO6JOO5UxUQ+SerEAw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "0c759504-84d8-4772-918f-14688e2c1632",
                            TwoFactorEnabled = false,
                            UserName = "contact@cegeka.be",
                            AantalBegeleidendeMedewerkers = 33,
                            AantalITMedewerkers = 200,
                            AantalMedewerkers = 233,
                            Adres = "Kempische Steenweg 307",
                            BedrijfspromotorId = 1,
                            ContactpersoonId = 1,
                            Gemeente = "Hasselt",
                            Postcode = "3500"
                        },
                        new
                        {
                            Id = 12,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "18ca2088-af4c-4d2c-bd33-d85bc8072c75",
                            Email = "contact@tesla.be",
                            EmailConfirmed = true,
                            IsBedrijf = true,
                            LockoutEnabled = true,
                            Naam = "Tesla",
                            NormalizedEmail = "CONTACT@TESLA.BE",
                            NormalizedUserName = "CONTACT@TESLA.BE",
                            PasswordHash = "AQAAAAEAACcQAAAAEE3MADTcj5R9NBdPZGuSrqvcfisB2jZdZoPa3+AbxcGsaSOQAO6JOO5UxUQ+SerEAw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "77a836f4-31e6-478b-b052-7e5075c9edc6",
                            TwoFactorEnabled = false,
                            UserName = "contact@tesla.be",
                            AantalBegeleidendeMedewerkers = 66,
                            AantalITMedewerkers = 600,
                            AantalMedewerkers = 666,
                            Adres = "Boomse Steenweg 8",
                            BedrijfspromotorId = 2,
                            ContactpersoonId = 2,
                            Gemeente = "Aartselaar",
                            Postcode = "2630"
                        },
                        new
                        {
                            Id = 13,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "aca9b812-a4f9-4ed1-8fb5-7dee4351f264",
                            Email = "contact@microsoft.nl",
                            EmailConfirmed = true,
                            IsBedrijf = true,
                            LockoutEnabled = true,
                            Naam = "Microsoft Nederland",
                            NormalizedEmail = "CONTACT@MICROSOFT.NL",
                            NormalizedUserName = "CONTACT@MICROSOFT.NL",
                            PasswordHash = "AQAAAAEAACcQAAAAEE3MADTcj5R9NBdPZGuSrqvcfisB2jZdZoPa3+AbxcGsaSOQAO6JOO5UxUQ+SerEAw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "4089f88a-83a2-4e39-8c96-914fad6e82db",
                            TwoFactorEnabled = false,
                            UserName = "contact@microsoft.nl",
                            AantalBegeleidendeMedewerkers = 365,
                            AantalITMedewerkers = 3648,
                            AantalMedewerkers = 4013,
                            Adres = "Evert van de Beekstraat 354",
                            BedrijfspromotorId = 3,
                            ContactpersoonId = 3,
                            Gemeente = "Schiphol",
                            Postcode = "1118CZ"
                        },
                        new
                        {
                            Id = 14,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "685b1b50-4d88-48de-9805-a49b0ffc2682",
                            Email = "contact@dell.be",
                            EmailConfirmed = true,
                            IsBedrijf = true,
                            LockoutEnabled = true,
                            Naam = "Dell",
                            NormalizedEmail = "CONTACT@DELL.BE",
                            NormalizedUserName = "CONTACT@DELL.BE",
                            PasswordHash = "AQAAAAEAACcQAAAAEE3MADTcj5R9NBdPZGuSrqvcfisB2jZdZoPa3+AbxcGsaSOQAO6JOO5UxUQ+SerEAw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "b13501f8-4deb-4815-99f5-2362b0a9aeba",
                            TwoFactorEnabled = false,
                            UserName = "contact@dell.be",
                            AantalBegeleidendeMedewerkers = 100,
                            AantalITMedewerkers = 1000,
                            AantalMedewerkers = 1100,
                            Adres = "Doornveld 130",
                            BedrijfspromotorId = 4,
                            ContactpersoonId = 4,
                            Gemeente = "Asse",
                            Postcode = "1731"
                        });
                });

            modelBuilder.Entity("Stage_API.Domain.Reviewer", b =>
                {
                    b.HasBaseType("Stage_API.Domain.User");

                    b.Property<bool>("IsCoordinator")
                        .HasColumnType("bit");

                    b.HasDiscriminator().HasValue("Reviewer");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "575a74b2-de85-42dc-8768-797d30f62b9f",
                            Email = "Marijke.Willems@pxl.be",
                            EmailConfirmed = true,
                            IsBedrijf = false,
                            LockoutEnabled = true,
                            Naam = "Willems",
                            NormalizedEmail = "MARIJKE.WILLEMS@PXL.BE",
                            NormalizedUserName = "MARIJKE.WILLEMS@PXL.BE",
                            PasswordHash = "AQAAAAEAACcQAAAAEE3MADTcj5R9NBdPZGuSrqvcfisB2jZdZoPa3+AbxcGsaSOQAO6JOO5UxUQ+SerEAw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "9e319446-0038-4677-8e09-f7d1087df9e9",
                            TwoFactorEnabled = false,
                            UserName = "marijke.willems@pxl.be",
                            Voornaam = "Marijke",
                            IsCoordinator = true
                        },
                        new
                        {
                            Id = 2,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "2b60579a-e7c1-4560-98da-c29157710dc1",
                            Email = "Kris.Hermans@pxl.be",
                            EmailConfirmed = true,
                            IsBedrijf = false,
                            LockoutEnabled = true,
                            Naam = "Hermans",
                            NormalizedEmail = "KRIS.HERMANS@PXL.BE",
                            NormalizedUserName = "KRIS.HERMANS@PXL.BE",
                            PasswordHash = "AQAAAAEAACcQAAAAEE3MADTcj5R9NBdPZGuSrqvcfisB2jZdZoPa3+AbxcGsaSOQAO6JOO5UxUQ+SerEAw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "cbf1aa26-9706-4c51-a3c0-9900d4ce1557",
                            TwoFactorEnabled = false,
                            UserName = "kris.hermans@pxl.be",
                            Voornaam = "Kris",
                            IsCoordinator = false
                        },
                        new
                        {
                            Id = 3,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "b95ce85e-c6cd-4e80-ac9b-ae6d3815c856",
                            Email = "Lowie.Vangaal@pxl.be",
                            EmailConfirmed = true,
                            IsBedrijf = false,
                            LockoutEnabled = true,
                            Naam = "Vangaal",
                            NormalizedEmail = "LOWIE.VANGAAL@PXL.BE",
                            NormalizedUserName = "LOWIE.VANGAAL@PXL.BE",
                            PasswordHash = "AQAAAAEAACcQAAAAEE3MADTcj5R9NBdPZGuSrqvcfisB2jZdZoPa3+AbxcGsaSOQAO6JOO5UxUQ+SerEAw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "5463c628-f387-4c01-9150-7e436300b83b",
                            TwoFactorEnabled = false,
                            UserName = "lowie.vangaal@pxl.be",
                            Voornaam = "Lowie",
                            IsCoordinator = false
                        },
                        new
                        {
                            Id = 4,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "f0ae34f0-7c86-4969-9184-61345e73c929",
                            Email = "arno.barzan@pxl.be",
                            EmailConfirmed = true,
                            IsBedrijf = false,
                            LockoutEnabled = true,
                            Naam = "Barzan",
                            NormalizedEmail = "ARNO.BARZAN@PXL.BE",
                            NormalizedUserName = "ARNO.BARZAN@PXL.BE",
                            PasswordHash = "AQAAAAEAACcQAAAAEE3MADTcj5R9NBdPZGuSrqvcfisB2jZdZoPa3+AbxcGsaSOQAO6JOO5UxUQ+SerEAw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "a17f8e77-32a0-4f12-85d0-b71a95888d3f",
                            TwoFactorEnabled = false,
                            UserName = "arno.barzan@pxl.be",
                            Voornaam = "Arno",
                            IsCoordinator = false
                        });
                });

            modelBuilder.Entity("Stage_API.Domain.Student", b =>
                {
                    b.HasBaseType("Stage_API.Domain.User");

                    b.Property<int?>("StagevoorstelId")
                        .HasColumnType("int");

                    b.HasIndex("StagevoorstelId");

                    b.HasDiscriminator().HasValue("Student");

                    b.HasData(
                        new
                        {
                            Id = 5,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "b4e55d03-05a6-4144-9975-35a3be58d863",
                            Email = "pieter.janssen@student.pxl.be",
                            EmailConfirmed = true,
                            IsBedrijf = false,
                            LockoutEnabled = true,
                            Naam = "Janssen",
                            NormalizedEmail = "PIETER.JANSSEN@STUDENT.PXL.BE",
                            NormalizedUserName = "PIETER.JANSSEN@STUDENT.PXL.BE",
                            PasswordHash = "AQAAAAEAACcQAAAAEE3MADTcj5R9NBdPZGuSrqvcfisB2jZdZoPa3+AbxcGsaSOQAO6JOO5UxUQ+SerEAw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "b41d570a-d5a6-4e79-8134-07dd3f1a90ec",
                            TwoFactorEnabled = false,
                            UserName = "pieter.janssen@student.pxl.be",
                            Voornaam = "Pieter"
                        },
                        new
                        {
                            Id = 6,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "63d9783f-bb94-4884-af5a-72bace387a23",
                            Email = "milosz.boghe@student.pxl.be",
                            EmailConfirmed = true,
                            IsBedrijf = false,
                            LockoutEnabled = true,
                            Naam = "Boghe",
                            NormalizedEmail = "MILOSZ.BOGHE@STUDENT.PXL.BE",
                            NormalizedUserName = "MILOSZ.BOGHE@STUDENT.PXL.BE",
                            PasswordHash = "AQAAAAEAACcQAAAAEE3MADTcj5R9NBdPZGuSrqvcfisB2jZdZoPa3+AbxcGsaSOQAO6JOO5UxUQ+SerEAw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "ce0c5f15-1170-4f8f-90c2-756cbc64bbb9",
                            TwoFactorEnabled = false,
                            UserName = "milosz.boghe@student.pxl.be",
                            Voornaam = "Milosz",
                            StagevoorstelId = 2
                        },
                        new
                        {
                            Id = 7,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "50b67514-4ee4-4b91-a070-2d753ee9d970",
                            Email = "brent.leemans@student.pxl.be",
                            EmailConfirmed = true,
                            IsBedrijf = false,
                            LockoutEnabled = true,
                            Naam = "Leemans",
                            NormalizedEmail = "BRENT.LEEMANS@STUDENT.PXL.BE",
                            NormalizedUserName = "BRENT.LEEMANS@STUDENT.PXL.BE",
                            PasswordHash = "AQAAAAEAACcQAAAAEE3MADTcj5R9NBdPZGuSrqvcfisB2jZdZoPa3+AbxcGsaSOQAO6JOO5UxUQ+SerEAw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "6a222135-a6cd-4fca-b510-0caebc7e4677",
                            TwoFactorEnabled = false,
                            UserName = "brent.leemans@student.pxl.be",
                            Voornaam = "Brent",
                            StagevoorstelId = 1
                        },
                        new
                        {
                            Id = 8,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "bf11f546-7d70-4fe3-a852-d724d00efc0e",
                            Email = "ruben.vlassak@student.pxl.be",
                            EmailConfirmed = true,
                            IsBedrijf = false,
                            LockoutEnabled = true,
                            Naam = "Vlassak",
                            NormalizedEmail = "RUBEN.VLASSAK@STUDENT.PXL.BE",
                            NormalizedUserName = "RUBEN.VLASSAK@STUDENT.PXL.BE",
                            PasswordHash = "AQAAAAEAACcQAAAAEE3MADTcj5R9NBdPZGuSrqvcfisB2jZdZoPa3+AbxcGsaSOQAO6JOO5UxUQ+SerEAw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "61ccc054-24e4-417a-9c12-d17d1bd1d32a",
                            TwoFactorEnabled = false,
                            UserName = "ruben.vlassak@student.pxl.be",
                            Voornaam = "Ruben",
                            StagevoorstelId = 2
                        },
                        new
                        {
                            Id = 9,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "fd691ebf-c93b-4be5-9b51-45c4df17077e",
                            Email = "kaan.ozdemi@student.pxl.be",
                            EmailConfirmed = true,
                            IsBedrijf = false,
                            LockoutEnabled = true,
                            Naam = "Ozdemir",
                            NormalizedEmail = "KAAN.OZDEMI@STUDENT.PXL.BE",
                            NormalizedUserName = "KAAN.OZDEMI@STUDENT.PXL.BE",
                            PasswordHash = "AQAAAAEAACcQAAAAEE3MADTcj5R9NBdPZGuSrqvcfisB2jZdZoPa3+AbxcGsaSOQAO6JOO5UxUQ+SerEAw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "62e2343d-0fbb-4003-bda1-c475db1d2893",
                            TwoFactorEnabled = false,
                            UserName = "kaan.ozdemi@student.pxl.be",
                            Voornaam = "Kaan",
                            StagevoorstelId = 1
                        },
                        new
                        {
                            Id = 10,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "7784c73b-6222-499c-931f-35c1fc92171c",
                            Email = "lennert.schoenmakers@student.pxl.be",
                            EmailConfirmed = true,
                            IsBedrijf = false,
                            LockoutEnabled = true,
                            Naam = "Schoenmakers",
                            NormalizedEmail = "LENNERT.SCHOENMAKERS@STUDENT.PXL.BE",
                            NormalizedUserName = "LENNERT.SCHOENMAKERS@STUDENT.PXL.BE",
                            PasswordHash = "AQAAAAEAACcQAAAAEE3MADTcj5R9NBdPZGuSrqvcfisB2jZdZoPa3+AbxcGsaSOQAO6JOO5UxUQ+SerEAw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "8852c7e2-b971-4426-9ae1-8c9b5584a0a9",
                            TwoFactorEnabled = false,
                            UserName = "lennert.schoenmakers@student.pxl.be",
                            Voornaam = "Lennert"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.HasOne("Stage_API.Domain.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.HasOne("Stage_API.Domain.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.HasOne("Stage_API.Domain.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.HasOne("Stage_API.Domain.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Stage_API.Domain.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.HasOne("Stage_API.Domain.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Stage_API.Domain.Classes.Comment", b =>
                {
                    b.HasOne("Stage_API.Domain.Stagevoorstel", "Stagevoorstel")
                        .WithMany("Comments")
                        .HasForeignKey("StagevoorstelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Stage_API.Domain.User", "User")
                        .WithMany("Comments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Stage_API.Domain.Message", b =>
                {
                    b.HasOne("Stage_API.Domain.User", null)
                        .WithMany("Messages")
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("Stage_API.Domain.Relations.ReviewerStagevoorstelToegewezen", b =>
                {
                    b.HasOne("Stage_API.Domain.Reviewer", "Reviewer")
                        .WithMany("ToegewezenVoorstellen")
                        .HasForeignKey("ReviewerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Stage_API.Domain.Stagevoorstel", "Stagevoorstel")
                        .WithMany("ReviewersToegewezen")
                        .HasForeignKey("StagevoorstelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Stage_API.Domain.Review", b =>
                {
                    b.HasOne("Stage_API.Domain.Reviewer", "Reviewer")
                        .WithMany("Reviews")
                        .HasForeignKey("ReviewerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Stage_API.Domain.Stagevoorstel", "Stagevoorstel")
                        .WithMany("Reviews")
                        .HasForeignKey("StagevoorstelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Stage_API.Domain.ReviewerStagevoorstelFavoriet", b =>
                {
                    b.HasOne("Stage_API.Domain.Reviewer", "Reviewer")
                        .WithMany("VoorkeurVoorstellen")
                        .HasForeignKey("ReviewerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Stage_API.Domain.Stagevoorstel", "Stagevoorstel")
                        .WithMany("ReviewersFavorieten")
                        .HasForeignKey("StagevoorstelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Stage_API.Domain.Stagevoorstel", b =>
                {
                    b.HasOne("Stage_API.Domain.Bedrijf", "Bedrijf")
                        .WithMany("Stagevoorstellen")
                        .HasForeignKey("BedrijfId");
                });

            modelBuilder.Entity("Stage_API.Domain.StudentStagevoorstelFavoriet", b =>
                {
                    b.HasOne("Stage_API.Domain.Stagevoorstel", "Stagevoorstel")
                        .WithMany("StudentenFavorieten")
                        .HasForeignKey("StagevoorstelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Stage_API.Domain.Student", "Student")
                        .WithMany("FavorieteOpdrachten")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Stage_API.Domain.Bedrijf", b =>
                {
                    b.HasOne("Stage_API.Domain.Bedrijfspromotor", "Bedrijfspromotor")
                        .WithMany()
                        .HasForeignKey("BedrijfspromotorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Stage_API.Domain.Contactpersoon", "Contactpersoon")
                        .WithMany()
                        .HasForeignKey("ContactpersoonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Stage_API.Domain.Student", b =>
                {
                    b.HasOne("Stage_API.Domain.Stagevoorstel", "ToegewezenStageOpdracht")
                        .WithMany("StudentenToegewezen")
                        .HasForeignKey("StagevoorstelId")
                        .OnDelete(DeleteBehavior.SetNull);
                });
#pragma warning restore 612, 618
        }
    }
}
